[2025-06-23T19:26:26.664+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: relatorio_revendas_diario.creating_csv manual__2025-06-23T19:26:12.788543+00:00 [queued]>
[2025-06-23T19:26:26.691+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: relatorio_revendas_diario.creating_csv manual__2025-06-23T19:26:12.788543+00:00 [queued]>
[2025-06-23T19:26:26.692+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-23T19:26:26.789+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): creating_csv> on 2025-06-23 19:26:12.788543+00:00
[2025-06-23T19:26:26.801+0000] {standard_task_runner.py:60} INFO - Started process 158714 to run task
[2025-06-23T19:26:26.810+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'relatorio_revendas_diario', 'creating_csv', 'manual__2025-06-23T19:26:12.788543+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/DagEnviarRelatorioDesempenho.py', '--cfg-path', '/tmp/tmp8qs6ornm']
[2025-06-23T19:26:26.818+0000] {standard_task_runner.py:88} INFO - Job 132: Subtask creating_csv
[2025-06-23T19:26:27.008+0000] {task_command.py:423} INFO - Running <TaskInstance: relatorio_revendas_diario.creating_csv manual__2025-06-23T19:26:12.788543+00:00 [running]> on host 99f5714845f7
[2025-06-23T19:26:27.489+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='relatorio_revendas_diario' AIRFLOW_CTX_TASK_ID='creating_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T19:26:12.788543+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T19:26:12.788543+00:00'
[2025-06-23T19:26:27.511+0000] {logging_mixin.py:188} INFO - Erro ao 
[2025-06-23T19:26:27.511+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-23T19:26:27.528+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=relatorio_revendas_diario, task_id=creating_csv, execution_date=20250623T192612, start_date=20250623T192626, end_date=20250623T192627
[2025-06-23T19:26:27.719+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-23T19:26:27.757+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
